services:
  db:
    image: postgis/postgis
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kyochanpy
      POSTGRES_PASSWORD: kyochanpy
      POSTGRES_DB: map_data
      TZ: Asia/Tokyo
    volumes:
      - ./mock/db/postgres-data:/var/lib/postgresql/data
      - ./mock/db/initdb.d:/docker-entrypoint-initdb.d
    command: postgres -c max_connections=100 -c shared_buffers=256MB

  minio:
    image: minio/minio
    volumes:
      - ./mock/s3:/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: kyochanpy
      MINIO_ROOT_PASSWORD: kyochanpy
    command: server /minio --console-address ":9001"