services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3006:3306
    environment:
      MYSQL_ROOT_PASSWORD: kyochanpy
      TZ: Asia/Tokyo
    volumes:
      - ./mock/db/initdb.d:/docker-entrypoint-initdb.d
      - ./mock/db/conf.d:/etc/mysql/conf.d

  minio:
    image: minio/minio
    volumes:
      - ./mock/s3:/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: kyochanpy
      MINIO_ROOT_PASSWORD: kyochanpy
    command: server /minio --console-address ":9001"